### ISSUE TITLE
Password scoring in demo doesn't match main password-score page

### ISSUE THREAD

**Issue by bitwombat** [davidstutz/bootstrap-strength-meter#5]
aaad3 is scored at 12.72 by http://davidstutz.github.io/password-score/
aaad3E is scored higher at 14.92

However, on the demo page at http://davidstutz.de/bootstrap-strength-meter/
in the first demo under Call Plugin, the first password above is rated "strong" and the second "weak".

Am I misunderstanding how this is supposed to work, or is there a problem?

**Comment by davidstutz** [comment]
Good catch. There are three things:

1. The demo at http://davidstutz.github.io/password-score/ is outdated; please use http://davidstutz.github.io/password-score/ instead - I removed the gh-pages branch to make this clearer.
2. The demo of Password Score was not at the correct commit, also fixed that.
3. The strength (meaning the score) can actually change when the password gets longer. This might be unintuitive, but is actually intended. For example, a couple of (seemingly random) characters might be harder to crack, than the same password with one or two characters added such that an english or german word is recognized. In your example, however, it is mainly due to the keyboard options (because "e" and "3" are adjacent on both qwertz and qwerty keyboards). If, for example, you would remove the following part in the password score configuration file, your example would work:

```
    {
        'type': 'keyboard',
        'key': 'qwerty',
        'keyboard': Score.prototype.keyboards.QWERTY
     },
     {
        'type': 'keyboard',
        'key': 'qwertz',
        'keyboard': Score.prototype.keyboards.QWERTZ
     },
     {
        'type': 'keyboard',
        'key': 'qwerty_numpad',
        'keyboard': Score.prototype.keyboards.QWERTYNumpad
     },
     {
        'type': 'keyboard',
        'key': 'qwertz_numpad',
        'keyboard': Score.prototype.keyboards.QWERTZNumpad
     },
```

See https://github.com/davidstutz/password-score/blob/master/dist/js/password-score-options.js.
